[package]
name = "bevyml-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter-bevyml = { path = "../tree-sitter-bevyml" }
tree-sitter = "0.26.3"
bevy_derive = "0.17.3"
pollster = "0.4.0"
tokio = { version = "1.49.0", features = ["full"] }
