[package]
name = "bevyml-demo"
version = "0.1.0"
edition.workspace = true

[dependencies]
bevy.workspace = true
bevyml.workspace = true
bevyml-parser.workspace = true

[build-dependencies]
fs_extra.workspace = true
